### ISSUE TITLE
Factorio 1.1.74 update causes translations to hang on save load

### ISSUE THREAD

**Issue by lzldmb** [nihilistzsche/LtnManager#201]
#### Describe the Bug

After Factorio's latest update, the translations that take place on save load get stuck at 5%. Aside from the UI being stuck on the screen, I'm not sure if there are other impacts.

#### To Reproduce

1. Install Factorio 1.1.74
2. Load a save that has LTNManager

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

USER: cinebum

Upload the save file where the bug occured. If the file is too large for GitHub, use an alternative file service.

Please also provide your in-game username so I can reproduce the conditions exactly.

_IF YOU DO NOT UPLOAD A SAVE FILE AND PROVIDE YOUR USERNAME, THE BUG REPORT WILL BE IGNORED UNTIL YOU DO._

#### Log file
[factorio-current.log](https://github.com/nihilistzsche/LtnManager/files/10247191/factorio-current.log)
[K2 Trains.zip](https://github.com/nihilistzsche/LtnManager/files/10247184/K2.Trains.zip)

Attach `factorio-current.log`, found in Factorio's [user data directory](https://wiki.factorio.com/Application_directory#User_data_directory).

![2022-12-16_10-52-49](https://user-images.githubusercontent.com/8334912/208137762-eea6e025-7e9c-4eb4-960a-1f5e44f44a23.png)

**Comment by raiguard** [comment]
You need to update the Factorio Library. This issue has been fixed in a recent patch. L
