### ISSUE TITLE
LTN Manager button grayed out / can't open

### ISSUE THREAD

**Issue by ChuckSavage** [nihilistzsche/LtnManager#202]
#### Describe the Bug

The LTN Manager can't be accessed on current SEK2 map. It was working when I'd played a couple months back, and since I've come back to factorio not.

The button on the hot bar is grayed out, nor does hitting Shift+E (the hotkey I've assigned) open the manager.

![image](https://user-images.githubusercontent.com/844259/211000082-4b866563-cfb9-4ee4-af61-a4611fbb05ce.png)

![image](https://user-images.githubusercontent.com/844259/211000362-4d4bc4a6-4650-49d3-ac30-c0c1db5b1bf0.png)

https://www.dropbox.com/s/03u4w1pp28adbm3/SEK2%201%20077%201.zip?dl=0

In game name: Dune1411

[factorio-current.log](https://github.com/nihilistzsche/LtnManager/files/10359668/factorio-current.log)

I ran the game for a little while. Sometimes LTN Manager won't open until a train has made a delivery, but that wasn't the case in the last few days. I played for many hours over the last few days, and I could never get it to open.

(https://wiki.factorio.com/Application_directory#User_data_directory).

**Comment by ChuckSavage** [comment]
Hey - flib update fixed it for me today.

**Comment by nihilistzsche** [comment]
THats great to hear, glad it fixed itself.
