### ISSUE TITLE
GUI Unifier Button

### ISSUE THREAD

**Issue by dtoxic47** [nihilistzsche/LtnManager#206]
#### Describe the solution you'd like

A button for opening the manager from the top left corner when using mod GUI Unifier

**Comment by nihilistzsche** [comment]
I looked, and I think this needs to be added on GUI Unifyer's side, so please request this from them.

**Comment by raiguard** [comment]
One of the last updates I did before handing this off was to add a remote interface for GUI unifyer to use. So it should be completely doable on their end.

**Comment by dtoxic47** [comment]
ok,ill open the issue there...thx guys

P.S
@raiguard i sent you a email concerning tapeline mod,but do not know if you received it

**Comment by raiguard** [comment]
I received it, no worries. I just haven't gotten to my email queue in a while.

**Comment by dtoxic47** [comment]
Awesome!
