### ISSUE TITLE
Ability to zoom to the train from train tab.

### ISSUE THREAD

**Issue by ajklotz** [nihilistzsche/LtnManager#211]
#### Is your feature request related to a problem? Please describe.

In Space Exploration, trains will be used across many surfaces. It is hard to tell which surface a train is at when looking at the trains tab. Need the ability to bring the train into view from LTN manager. Currently, clicking on a train only brings up the train GUI which then provides the 'open this location on the map' button, but that button doesn't work if the current view isn't the right surface.

**Comment by nihilistzsche** [comment]
The Train gui comes from flib it looks like, so I think you need to report this to raiguard through his mailing list.

**Comment by ajklotz** [comment]
> The Train gui comes from flib it looks like, so I think you need to report this to raiguard through his mailing list.

Okay, posted on his issues tracker. 

https://lists.sr.ht/~raiguard/factorio-mods-discuss/%3CCAP10XcehO1OX0KSSYiK4kD9fdmCO4TfjmLVMKVBtvNFKz%2B6BGQ%40mail.gmail.com%3E

**Comment by raiguard** [comment]
Unfortunately, this is a base game limitation. You cannot open the map on another surface. LTN Manager will need to add code to interface with Space Exploration in order to facilitate this.

**Comment by nihilistzsche** [comment]
Hey raiguard, you don't need to post here, I am subscribed to your mailing lists so I see them there, just fyi :)
