### ISSUE TITLE
Non-recoverable Error(0.4.16)

### ISSUE THREAD

**Issue by abcnever** [nihilistzsche/LtnManager#212]
#### Describe the Bug

Not sure what happened. I was just afking and then this error happened. I recently installed a new mod for this save https://mods.factorio.com/mod/fast_trans. Before this mod, I never encountered any errors. 

#### To Reproduce

1. Load the save file
2. Wait a little bit
3. See error

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Username: abcnever

Save file: [Google Drive](https://drive.google.com/file/d/1-c_lH8VO4ijkkbX-kgJVuRZ_YiAeeXVQ/view?usp=sharing)

#### Log file

[factorio-current.log](https://github.com/nihilistzsche/LtnManager/files/10714844/factorio-current.log)

**Comment by nihilistzsche** [comment]
Fixed in 0.4.17.

**Comment by abcnever** [comment]
Thank you so much! @nihilistzsche
