### ISSUE TITLE
Shift Click does not work with different Surfaces

### ISSUE THREAD

**Issue by some0nenew** [nihilistzsche/LtnManager#213]
If you shift-click a Station in the LTN manager to jump to it, and said station is on a different Surface you don't jump to the surface of the station but only to the coordinates on the same surface you are currently on 

Open LTN Manager
Go to Alarms
Shift click on an alarm thats on a different surface

Jump to a point on the same surface

Username: Kallinger

Savefile: https://privatenextcloud.ddns.net/nextcloud/index.php/s/CnjBwgdc7pX8XiS
Expire on the 18/02/2023

#### Log file

[factorio-previous.log](https://github.com/nihilistzsche/LtnManager/files/10714942/factorio-previous.log)

**Comment by nihilistzsche** [comment]
Should be fixed in 0.4.17, please let me know if it still does not work.

**Comment by nihilistzsche** [comment]
Turns out the fix isnt what i thought it was.

**Comment by nihilistzsche** [comment]
Okay, try the new 0.4.17 that should hopefully work.

**Comment by some0nenew** [comment]
If i click on this one here: 
![image](https://user-images.githubusercontent.com/87366654/218337179-dd14534b-f898-425c-9dde-5537ac115037.png)
i get this error:
![image](https://user-images.githubusercontent.com/87366654/218337058-d0abbd44-2a76-4935-a444-eda7323fc863.png)

Uploaded the current Save in same share link I provided before.
