### ISSUE TITLE
Crash while shift-clicking on a station from the train tab.

### ISSUE THREAD

**Issue by ajklotz** [nihilistzsche/LtnManager#214]
The mod LTN Manager (0.4.17) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
LuaEntity belongs to surface Morozko (index 10) but a LuaEntity belonging to surface Nauvis Orbit (index 2) was expected.
stack traceback:
	[C]: in function 'zoom_to_world'
	__LtnManager__/scripts/gui/actions.lua:91: in function 'func'
	__LtnManager__/scripts/gui/index.lua:81: in function 'dispatch'
	__LtnManager__/control.lua:127: in function 'handle_gui_event'
	__LtnManager__/control.lua:136: in function <__LtnManager__/control.lua:133>

**Comment by nihilistzsche** [comment]
Ah this may be unsolvable for me then.  I will leave this open for now and will fix this particular error soon but I may just have to ignore shift-clicking when not on the same surface.  Ill do some more digging soon.

**Comment by ajklotz** [comment]
If I satellite view another surface, then shift click a station on that same surface, it brings up that station in map mode, not satellite mode. No crash. 

If I satellite view another surface, then shift click a station on some other surface, I crash.

**Comment by nihilistzsche** [comment]
That is what I expected would happen.  For now just avoid shift-clicking stations on another surface without satellite viewing the appropriate station first.  I plan to look into raiguard's suggestion to interface with space exploration soon, but I can't give a timetable for when I will be able to do that.

**Comment by maritz** [comment]
With the current update (0.4.21) I get a different error now on this.
Since you closed #218, I guess here is more appropriate to continue this?

```
Error while running event LtnManager::on_gui_click (ID 1)
__LtnManager__/scripts/gui/actions.lua:94: attempt to call global 'remote_call' (a nil value)
stack traceback:
	__LtnManager__/scripts/gui/actions.lua:94: in function 'func'
	__LtnManager__/scripts/gui/index.lua:81: in function 'dispatch'
	__LtnManager__/control.lua:127: in function 'handle_gui_event'
	__LtnManager__/control.lua:136: in function <__LtnManager__/control.lua:133>
```

I have Space Exploration installed and satellite view is unlocked. Shift+clicking on a train station on a different surface leads to this error, regardless of whether I already am in satellite view or not.

**Comment by maritz** [comment]
Now this:

```
The mod LTN Manager (0.4.22) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event LtnManager::on_gui_click (ID 1)
Unknown interface: space-exloration
stack traceback:
	[C]: in function 'call'
	__LtnManager__/scripts/gui/actions.lua:99: in function 'func'
	__LtnManager__/scripts/gui/index.lua:81: in function 'dispatch'
	__LtnManager__/control.lua:127: in function 'handle_gui_event'
	__LtnManager__/control.lua:136: in function <__LtnManager__/control.lua:133>
```

**Comment by nihilistzsche** [comment]
Thank you for catching these, please redownload 0.4.22

**Comment by maritz** [comment]
Now it doesn't cause an error anymore, but it simply closes the LTN Manager GUI and then nothing happens. (no changing of surface or view location)

Same for already being in satellite, map or normal view.

**Comment by nihilistzsche** [comment]
Interesting, if it no longer crashes I'll leave this alone for now, but will ask on the Space Exploration discord soon how I should handle this.

**Comment by maritz** [comment]
The problem is that `surface.name` does not map 1:1 to `zone_name`. 

I'll look into how to properly get the zone name later and make a PR if I can figure it out.
