### ISSUE TITLE
Game freezes

### ISSUE THREAD

**Issue by Dominiquini** [nihilistzsche/LtnManager#217]
#### Describe the Bug

When I try to open the Windows GUI, my game is freezing for almost 1 minute! And while the Window in open, my FPS/UPS drops to below 20FPS! Normally it runs between 45 and 55 FPS

#### To Reproduce

1. Use the keyboard shortcut / or button to open the Window GUI
2. The game freezes for a while before the Windows is opened!

Be certain to reproduce the issue on the same save file that you upload.

#### Save file & Username

Entire personal Factorio folder, with the saved game and all my mods:
https://www.dropbox.com/scl/fo/3o1jg0bblg3vpfeg91kek/h?dl=0&rlkey=kly3f352ieww2658zlc0imp12

#### Log file

[factorio-current.log](https://github.com/nihilistzsche/LtnManager/files/11126102/factorio-current.log)

#### Game version

Factorio 1.1.80

**Comment by lukaskollmer** [comment]
I've been running into the UPS drop issue as well, though my UPS only drops when the stations tab is selected in LTN manager; switching to eg the inventory tab will cause the UPS to go up again.

The weird thing is that the UPS drop persists even after the LTN manager window is closed, if the stations tab was selected when closing the window.

**Comment by Dominiquini** [comment]
> I've been running into these issues as well, though my UPS only dropped when selecting the stations tab in LTN manager; switching to eg the inventory tab will cause the UPS to go up again.
> 
> The weird thing is that the UPS drop persists even after the LTN manager window is closed, if the stations tab was selected when closing the window.
> 
> In the past, I sometimes had UPS drops in the stations tab, but more recently trying to open the stations tab has started to completely freeze the game. I tried to just wait for a couple of minutes hoping that it might continue working eventually, but that is not the case.
> 
> Update: after trying to look into this a bit more, it seems to me that the underlying issue here is that either the mod or Factorio itself is having issues rendering the list of train stops. I had a look at Factorio's stack trace while hanging after switching to the stations tab, and essentially all of the GameUpdate thread's work was calculating widget frames and sizes, so maybe that's the issue here? (I have ~4000 train stations, which has already caused the stations list to become really slow in the past, though it never caused a complete hang...)

The same problem here! Your explanations is much better. But in my case, the game resume after 1 or 2 minutes after I opened the Stations tab, but I only have 750 stations!

Thanks

**Comment by Dominiquini** [comment]
+1

**Comment by ComradeEcho** [comment]
In Factorio version 1.1.79 (March 30th) `on_gui_hover` was implemented, but accidentally caused a massive performance hit to tooltip creation (there's about 4 tooltips created per train station, at a current cost of 10ms+ each)

Developer says this has been fixed for the future 1.1.82 release

![image](https://user-images.githubusercontent.com/4523694/234435468-cdfb5131-8a8d-4c9e-8478-51d8909e9f34.png)

**Comment by nihilistzsche** [comment]
This has been reported fixed on my discord in 1.1.82 (which is now in experimental).
