### ISSUE TITLE
Zoomed to very close on shift+click on station

### ISSUE THREAD

**Issue by maritz** [nihilistzsche/LtnManager#224]
#### Describe the Bug

Since the 0.4.21 (or maybe 0.4.20), when shift+clicking on a station, it opens the map view incredibly zoomed in:
![image](https://user-images.githubusercontent.com/159633/236177929-2377292b-2d09-4033-87ca-e36b441cf0a0.png)

Closing the map view reveals just *how* zoomed in that is:
![image](https://user-images.githubusercontent.com/159633/236178002-f581f838-7a9b-4f31-87ab-78dc6ca03496.png)

#### To Reproduce

1. Shift+Click on a station name in LTN Manager
2. Be zoomed in

**Comment by nihilistzsche** [comment]
Are you able to zoom out?

**Comment by maritz** [comment]
Yes, zooming out still works. Takes a few scrolls to even get to the maximum zoom in you can normally achieve.

**Comment by nihilistzsche** [comment]
Okay I will look into this at some point, but if you can still zoom out I will consider it a very low priority to fix.

**Comment by maritz** [comment]
I'm pretty sure I can just fix it and send you a PR, if you want. (never done any factorio modding, but this fix looks simple enough to me)

**Comment by nihilistzsche** [comment]
PRs are always welcome.
