### ISSUE TITLE
LTN Manager button grayed out

### ISSUE THREAD

**Issue by maciekish** [nihilistzsche/LtnManager#232]
#### Describe the Bug

Hi, i have a new install of Factorio and tried loading my save from another computer. Something about translating flashed up on initial load and the LTN button is disabled.

<img width="705" alt="image" src="https://github.com/nihilistzsche/LtnManager/assets/442007/fd956a9b-f9c7-476e-bd56-095e965082b4">

All my mods are up to date and work on the other machine:

<img width="698" alt="image" src="https://github.com/nihilistzsche/LtnManager/assets/442007/c2854955-3d94-47fc-9376-4e74ec8ff31a">

#### To Reproduce

1. Load save
2. LTN Manager button is disabled

#### Save file & Username

https://sprend.com/download?C=e5b8cd169eda4ed2b89bbea28cad5f73

#### Log file
[factorio-current.log](https://github.com/nihilistzsche/LtnManager/files/13877985/factorio-current.log)

**Comment by maciekish** [comment]
Tried clearing my %AppData%\Factorio folder and reinstalling the mod, same issue. Factorio 1.1.100 (61920, win64)

**Comment by maciekish** [comment]
Downgrading to 0.4.17 works. Havent tried any versions inbetween.

**Comment by maciekish** [comment]
Nevermind, the button came alive after a minute or so...

**Comment by nihilistzsche** [comment]
Yea, for the technical reason this happens is that its disabled why the dictionary is translating.  This is something flib does, and honestly not something I know that much about except that.
